
print('=======================O NUMERO MAIOR==================================')
def num_maior(num1, num2):      
       num1 = int(input('DIGITE O PRIMEIRO NUMERO:   '))
       num2 = int(input('DIGITE O SEGUNDO NUMERO:    '))
       return max(num1,num2)

print('=======================================================================')
print( f'O MAIOR NUMERO DIGITADO NO TERMINAL FOI : {num_maior(10,20)}')
print('=======================================================================')

